import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

interface TemplateFile {
  path: string;
  content: string;
}

const templates: Record<string, TemplateFile[]> = {
  autoaufbereitung: [
    { path: "index.html", content: generateIndexHTML("autoaufbereitung") },
    { path: "styles.css", content: generateBaseCSS() },
    { path: "script.js", content: generateBaseJS() },
    { path: "README.md", content: generateReadme("autoaufbereitung") },
  ],
};

function generateIndexHTML(templateName: string): string {
  return `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{COMPANY_NAME}}</title>
  <link rel="stylesheet" href="styles.css">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-black text-white">
  <!-- Generated from template: ${templateName} -->

  <header class="fixed top-0 left-0 right-0 z-50 bg-black/80 backdrop-blur-md border-b border-white/10">
    <div class="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
      <h1 class="text-2xl font-bold">{{COMPANY_NAME}}</h1>
      <nav class="hidden md:flex space-x-6">
        <a href="#services" class="hover:text-orange-400 transition-colors">Leistungen</a>
        <a href="#about" class="hover:text-orange-400 transition-colors">Über uns</a>
        <a href="#contact" class="hover:text-orange-400 transition-colors">Kontakt</a>
      </nav>
      <a href="tel:{{PHONE}}" class="px-4 py-2 bg-gradient-to-r from-orange-500 to-pink-400 text-black font-bold rounded-lg">
        Jetzt anrufen
      </a>
    </div>
  </header>

  <main class="pt-20">
    <section class="min-h-screen flex items-center justify-center px-4">
      <div class="text-center max-w-4xl">
        <h2 class="text-6xl md:text-8xl font-bold mb-6 bg-gradient-to-r from-orange-500 to-pink-400 bg-clip-text text-transparent">
          {{COMPANY_NAME}}
        </h2>
        <p class="text-2xl md:text-3xl text-gray-300 mb-8">
          {{TAGLINE}}
        </p>
        <a href="#contact" class="inline-block px-8 py-4 bg-gradient-to-r from-orange-500 to-pink-400 hover:from-orange-600 hover:to-pink-500 text-black font-bold rounded-lg text-lg transition-all">
          Jetzt Termin vereinbaren
        </a>
      </div>
    </section>

    <section id="services" class="py-20 px-4">
      <div class="max-w-7xl mx-auto">
        <h2 class="text-4xl md:text-5xl font-bold text-center mb-12">Unsere Leistungen</h2>
        <div class="grid md:grid-cols-3 gap-8">
          <!-- Services will be injected here -->
          {{SERVICES}}
        </div>
      </div>
    </section>

    <section id="contact" class="py-20 px-4 bg-gradient-to-b from-black to-gray-900">
      <div class="max-w-4xl mx-auto text-center">
        <h2 class="text-4xl md:text-5xl font-bold mb-8">Kontaktieren Sie uns</h2>
        <div class="space-y-4 text-lg">
          <p><strong>Telefon:</strong> <a href="tel:{{PHONE}}" class="text-orange-400 hover:text-orange-300">{{PHONE}}</a></p>
          <p><strong>E-Mail:</strong> <a href="mailto:{{EMAIL}}" class="text-orange-400 hover:text-orange-300">{{EMAIL}}</a></p>
          <p><strong>Adresse:</strong> {{ADDRESS}}, {{ZIP}} {{CITY}}</p>
        </div>
      </div>
    </section>
  </main>

  <footer class="bg-black border-t border-white/10 py-8">
    <div class="max-w-7xl mx-auto px-4 text-center text-gray-400">
      <p>&copy; 2025 {{COMPANY_NAME}}. Alle Rechte vorbehalten.</p>
    </div>
  </footer>

  <script src="script.js"></script>
</body>
</html>`;
}

function generateBaseCSS(): string {
  return `/* Generated by Webflix - Custom Styles */

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
}

.service-card {
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 12px;
  padding: 2rem;
  transition: all 0.3s ease;
}

.service-card:hover {
  background: rgba(255, 255, 255, 0.1);
  border-color: rgba(249, 115, 22, 0.5);
  transform: translateY(-4px);
}
`;
}

function generateBaseJS(): string {
  return `// Generated by Webflix - Interactive Features

document.addEventListener('DOMContentLoaded', function() {
  console.log('Website loaded successfully!');

  // Smooth scroll for navigation links
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault();
      const target = document.querySelector(this.getAttribute('href'));
      if (target) {
        target.scrollIntoView({ behavior: 'smooth' });
      }
    });
  });

  // Mobile menu toggle (if needed)
  const mobileMenuBtn = document.querySelector('[data-mobile-menu]');
  const mobileMenu = document.querySelector('[data-mobile-menu-content]');

  if (mobileMenuBtn && mobileMenu) {
    mobileMenuBtn.addEventListener('click', () => {
      mobileMenu.classList.toggle('hidden');
    });
  }
});
`;
}

function generateReadme(templateName: string): string {
  return `# Website - Generated by Webflix

This website was automatically generated from the **${templateName}** template.

## Deployment Instructions

### Option 1: Netlify (Recommended)
1. Go to https://app.netlify.com/drop
2. Drag and drop this entire folder
3. Your site will be live in seconds!

### Option 2: Vercel
1. Install Vercel CLI: \`npm i -g vercel\`
2. Run \`vercel\` in this directory
3. Follow the prompts

### Option 3: Traditional Hosting
1. Upload all files to your web server via FTP
2. Make sure index.html is in the root directory

## Customization

You can edit the following placeholders in index.html:
- {{COMPANY_NAME}} - Your company name
- {{TAGLINE}} - Your tagline
- {{PHONE}} - Your phone number
- {{EMAIL}} - Your email address
- {{ADDRESS}} - Your street address
- {{ZIP}} - Your postal code
- {{CITY}} - Your city
- {{SERVICES}} - Service cards HTML

## Support

For support, contact: support@webflix.de

---

Generated: ${new Date().toISOString()}
Template: ${templateName}
`;
}

function injectContent(html: string, content: any): string {
  let result = html;

  const replacements: Record<string, string> = {
    '{{COMPANY_NAME}}': content.companyInfo?.name || 'Ihr Unternehmen',
    '{{TAGLINE}}': content.companyInfo?.tagline || 'Ihr Slogan',
    '{{PHONE}}': content.companyInfo?.phone || '+49 123 456789',
    '{{EMAIL}}': content.companyInfo?.email || 'info@example.com',
    '{{ADDRESS}}': content.companyInfo?.address || 'Musterstraße 123',
    '{{ZIP}}': content.companyInfo?.zip || '12345',
    '{{CITY}}': content.companyInfo?.city || 'Musterstadt',
  };

  for (const [key, value] of Object.entries(replacements)) {
    result = result.replace(new RegExp(key, 'g'), value);
  }

  if (content.services && Array.isArray(content.services)) {
    const servicesHTML = content.services.map((service: any) => `
      <div class="service-card">
        <h3 class="text-2xl font-bold mb-4">${service.name || service.title}</h3>
        <p class="text-gray-300 mb-4">${service.description || ''}</p>
        ${service.price ? `<p class="text-orange-400 font-bold">${service.price}</p>` : ''}
      </div>
    `).join('');
    result = result.replace('{{SERVICES}}', servicesHTML);
  } else {
    result = result.replace('{{SERVICES}}', '<p class="text-gray-400">Keine Services definiert</p>');
  }

  return result;
}

async function createZipFile(files: TemplateFile[]): Promise<Uint8Array> {
  const encoder = new TextEncoder();
  const zipData: Uint8Array[] = [];

  for (const file of files) {
    const content = encoder.encode(file.content);
    zipData.push(content);
  }

  return new Uint8Array(zipData.flat());
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const { website_id } = await req.json();

    const { data: website, error: websiteError } = await supabase
      .from("generated_websites")
      .select("*")
      .eq("id", website_id)
      .single();

    if (websiteError || !website) {
      throw new Error("Website not found");
    }

    const templateFiles = templates[website.template_name] || templates.autoaufbereitung;

    const processedFiles = templateFiles.map(file => ({
      path: file.path,
      content: file.path === 'index.html'
        ? injectContent(file.content, website.injected_content)
        : file.content,
    }));

    const zipContent = await createZipFile(processedFiles);

    await supabase
      .from("generated_websites")
      .update({ zip_generated: true })
      .eq("id", website_id);

    return new Response(zipContent, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${website.slug}.zip"`,
      },
    });
  } catch (error: any) {
    console.error("Error generating ZIP:", error);
    return new Response(
      JSON.stringify({ error: error.message || "Internal server error" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
